apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: test
  labels:
    app: adservice
spec:
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
        - name: adservice
          image: drnau/adservice
          ports:
            - containerPort: 9555
          env:
            - name: PORT
              value: "9555"
            - name: DISABLE_TRACING
              value: "false"
            - name: DISABLE_DEBUGGER
              value: "false"
            - name: DISABLE_PROFILER
              value: "false"
