apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: test
  labels:
    app: cartservice
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: cartservice
          image: drnau/cart_service
          env:
            - name: REDIS_
              value: redis:6379
