apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  namespace: test
  labels:
    app: emailservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
        - name: emailservice
          image: drnau/email_service
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"

