apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: test
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: drnau/frontend
          ports:
            - containerPort: 8080
          env:
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: productcatalogservice:3550
            - name: SHIPPING_SERVICE_ADDR
              value: shippingservice:50051
            - name: CART_SERVICE_ADDR
              value: cartservice:7070
            - name: CURRENCY_SERVICE_ADDR
              value: currencyservice:7000
            - name: CHECKOUT_SERVICE_ADDR
              value: checkoutservice:5050
            - name: RECOMMENDATION_SERVICE_ADDR
              value: recommendationservice:8080
            - name: AD_SERVICE_ADDR
              value: adservice:9555
            - name: PORT
              value: "8080"
