apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: test
  labels:
    app: paymentservice
spec:
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: paymentservice
          image: drnau/payment_service
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"

