apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  namespace: test
  labels:
    app: productcatalogservice
spec:
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
        - name: productcatalogservice
          image: drnau/productcatalogservice
          ports:
            - containerPort: 3550
          env:
            - name: PORT
              value: "3550"

