apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  namespace: test
  labels:
    app: shippingservice
spec:
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
        - name: shippingservice
          image: drnau/shippingservice
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"
