apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: test
spec:
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:7.16.1
          ports:
            - containerPort: 9200
              name: elasticsearch
