apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: test
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: 9200