apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: test
  labels:
    app: kibana
spec:
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.16.1
          ports:
            - containerPort: 9200
