apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: test
  labels:
    app: adservice
spec:
  selector:
    app: adservice
  type: ClusterIP
  ports:
    - port: 9555
      targetPort: 9555
