apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: test
  labels:
    app: checkoutservice
spec:
  selector:
    app: checkoutservice
  type: ClusterIP
  ports:
    - port: 5050
