apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: test
  labels:
    app: currencyservice
spec:
  selector:
    app: currencyservice
  type: ClusterIP
  ports:
    - port: 7000
      targetPort: 7000
