apiVersion: v1
kind: Service
metadata:
  name: loadgenerator
  namespace: test
  labels:
    app: loadgenerator
spec:
  selector:
    app: loadgenerator
  type: NodePort
  ports:
    - port: 80
      nodePort: 32000
