apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  namespace: test
  labels:
    app: paymentservice
spec:
  selector:
    app: paymentservice
  type: ClusterIP
  ports:
    - port: 50052
      targetPort: 50051