apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: test
  labels:
    app: productcatalogservice
spec:
  selector:
    app: productcatalogservice
  type: ClusterIP
  ports:
    - port: 3550
      targetPort: 3550
