apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  namespace: test
  labels:
    app: recommendationservice
spec:
  selector:
    app: recommendationservice
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
    