apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  namespace: test
  labels:
    app: shippingservice
spec:
  selector:
    app: shippingservice
  type: ClusterIP
  ports:
    - port: 50051
      targetPort: 50051
